### ISSUE TITLE
Query Param - failed

### ISSUE THREAD

**Issue by Wade-BuildOtto** [nicholasgubbins/Serverless-Image-Resizer#17]
I am able to view the image without and param's but a soon as I add any I get a server error
I thought it might of had something to do with the image being in subfolders but I tried one from the root folder with the same issues.

I get the following error on the server.
Execution failed due to configuration error: Malformed Lambda proxy response

and to verify yes I have added binary support. 

thx,

**Comment by marcusmolchany** [comment]
hey @Wade-BuildOtto, do you have an example URL you can share so I can see the query params you're using? So you don't share it publicly, don't send your beginning of your api gateway url.

**Comment by Wade-BuildOtto** [comment]
here are some examples

execute-api.us-east-1.amazonaws.com/dev/apple-badge-155x60.png?w=100
execute-api.us-east-1.amazonaws.com/dev/JYt4tm2rmv/pfTPGgYGbE/images/uFL_Maxim-24-M.png?h=200

**Comment by Wade-BuildOtto** [comment]
any thoughts?

**Comment by Wade-BuildOtto** [comment]
I am really hoping to use this package, but I can't find what I am doing wrong.

**Comment by nicholasgubbins** [comment]
Hey could you share some of the lambda logs?

**Comment by nicholasgubbins** [comment]
Also both those urls fail with and without query parameter? Could you share another link that works without the query params

**Comment by nicholasgubbins** [comment]
@wade-buildotto

**Comment by Wade-BuildOtto** [comment]
here is the url link without query params

https://zohivcpzv1.execute-api.us-east-1.amazonaws.com/dev/JYt4tm2rmv/pfTPGgYGbE/images/uFL_Maxim-24-M.png

**Comment by zagreusinoz** [comment]
I have this issue too I'm afraid.  also, Cloudwatch doesn't seem to be getting configured so it's a bit difficult to try to problem solve.

**Comment by marcusmolchany** [comment]
@Wade-BuildOtto @zagreusinoz I've recreated the issue and am looking into it. Something with Cloudwatch change such that the logs are not automatically generated anymore. This should get those logs setup https://serverless-stack.com/chapters/api-gateway-and-lambda-logs.html

**Comment by marcusmolchany** [comment]
seeing this error in my API gateway logs
```
Execution failed due to configuration error: Malformed Lambda proxy response
```

working on getting logging setup in the lambdas

**Comment by zagreusinoz** [comment]
Thanks Marcus - in the meantime the pull request I gave actually solves the original 500 error problem (for me anyway)

**Comment by marcusmolchany** [comment]
tested @zagreusinoz's PR and that definitely fixed the issue here. @Wade-BuildOtto if you want to confirm that the latest `origin/master` fixes this for you I can do another release.

**Comment by Wade-BuildOtto** [comment]
yeah that fixed it, thank you

yeah!!! :-)
