### ISSUE TITLE
Testing Errors / Missing Jist Configuration

### ISSUE THREAD

**Issue by selected-pixel-jameson** [nicholasgubbins/Serverless-Image-Resizer#22]
I'm not sure if it got ignore or what exactly is happening since I'm not entirely familiar with jist but I'm trying to run the tests and I just get an error. I don't see anything related to the jist configuration that is discussed in the documentation. Did this not get committed to the repo?

**Comment by marcusmolchany** [comment]
hey @selected-pixel-jameson, have you installed the nod dependencies already? I just cloned the project into a new folder and the tests ran:

```
$ git clone https://github.com/nicholasgubbins/Serverless-Image-Resizer.git
$ yarn
$ yarn test
```

**Comment by selected-pixel-jameson** [comment]
Hmm.. I wasn’t using yarn. Just NPM. I have installed the npm dependencies. I have it running and working, just can’t get the tests to fire up. 

Jameson Parker
Owner & Software Engineer
www.selectedpixel.com
www.linkedin.com/in/jamesonwparker
(414) 395-5196

**Comment by marcusmolchany** [comment]
let me try installing with npm. which version of npm and node are you using?

**Comment by marcusmolchany** [comment]
I've just tried the same setup using npm and npm test and it worked. I'm using node `7.2.0` and npm `5.6.0`.

**Comment by selected-pixel-jameson** [comment]
Ok, I’ll see if I can figure anything else out. Thanks for the feedback. I’m working on adding an update that will store the sized images in their own folder so that you can easily clear out the images if needed.

Jameson Parker
Owner & Software Engineer
www.selectedpixel.com
www.linkedin.com/in/jamesonwparker
(414) 395-5196

**Comment by selected-pixel-jameson** [comment]
Switched my node version and reinstalled node packages and I'm making some progress.

**Comment by marcusmolchany** [comment]
awesome, excited to see the change that you're talking about
