### ISSUE TITLE
Refusing to install serverless-image-resizer as a dependency of itself

### ISSUE THREAD

**Issue by vipulsolanki8466** [nicholasgubbins/Serverless-Image-Resizer#24]
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "serverless-image-resizer"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install serverless-image-resizer as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dev/Desktop/Test/Serverless-Image-Resizer/npm-debug.log

**Comment by marcusmolchany** [comment]
Hey there, what do you have set for `name` in your `package.json`? Similar issue here: https://github.com/sindresorhus/gulp-imagemin/issues/7

**Comment by marcusmolchany** [comment]
based on the path in your error message (`/Users/dev/Desktop/Test/Serverless-Image-Resizer`) I'm going to assume that this was the case. Closing this issue, reopen if this did not fix it for you.
